elasticsearch:
  image:
    tag: 8.16.0
  global:
    kibanaEnabled: true
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0